brew "automake"
brew "autoconf"
brew "coreutils"
brew "libtool"
brew "cmake"
brew "cryptopp"
brew "pbc"
brew "openssl@1.1"
brew "readline"
brew "boost"
brew "qt"
brew "doxygen"
tap "nlohmann/json"
brew "nlohmann_json",  args: ["with-cmake"]
