//                                   _           _    __ _ _        //
//                                  | |         | |  / _(_) |       //
//    __ _  ___ _ __   ___ _ __ __ _| |_ ___  __| | | |_ _| | ___   //
//   / _` |/ _ \ '_ \ / _ \ '__/ _` | __/ _ \/ _` | |  _| | |/ _ \  //
//  | (_| |  __/ | | |  __/ | | (_| | ||  __/ (_| | | | | | |  __/  //
//   \__, |\___|_| |_|\___|_|  \__,_|\__\___|\__,_| |_| |_|_|\___|  //
//    __/ |                                                         //
//   |___/                                                          //
//                                                                  //
// Generated by:  libraries/chain_id/identify_chain.cpp             //
//                                                                  //
// Warning: This is a generated file, any changes made here will be //
// overwritten by the build process.  If you need to change what    //
// is generated here, you should use the CMake variable             //
// GRAPHENE_EGENESIS_JSON to specify an embedded genesis state.     //
//                                                                  //

/*
 * Copyright (c) 2015, Cryptonomex, Inc.
 * All rights reserved.
 *
 * This source code is provided for evaluation in private test networks only, until September 8, 2015. After this date, this license expires and
 * the code may not be used, modified or distributed for any purpose. Redistribution and use in source and binary forms, with or without modification,
 * are permitted until September 8, 2015, provided that the following conditions are met:
 *
 * 1. The code and/or derivative works are used only for private test networks consisting of no more than 10 P2P nodes.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <graphene/chain/protocol/types.hpp>
#include <graphene/egenesis/egenesis.hpp>

namespace graphene { namespace egenesis {

using namespace graphene::chain;

static const char genesis_json_array[132][40+1] =
{
"{\"initial_timestamp\":\"2017-03-09T14:26:4",
"0\",\"max_core_supply\":\"6000000000000000\",",
"\"initial_parameters\":{\"current_fees\":{\"p",
"arameters\":[[0,{\"fee\":10000000,\"price_pe",
"r_kbyte\":1000000000}],[1,{\"fee\":10000000",
"}],[2,{\"fee\":0}],[3,{}],[4,{\"basic_fee\":",
"500000000,\"premium_fee\":2000000000,\"pric",
"e_per_kbyte\":100000000}],[5,{\"fee\":10000",
"0000,\"price_per_kbyte\":100000000}],[6,{\"",
"fee\":500000000}],[7,{\"symbol3\":\"50000000",
"000\",\"symbol4\":\"20000000000\",\"long_symbo",
"l\":500000000,\"price_per_kbyte\":10}],[8,{",
"\"fee\":200000000,\"price_per_kbyte\":10}],[",
"9,{\"fee\":100000000}],[10,{\"fee\":20000000",
"0,\"price_per_kbyte\":100000000}],[11,{\"fe",
"e\":1}],[12,{\"fee\":\"5000000000\"}],[13,{\"f",
"ee\":200000000}],[14,{\"fee\":10}],[15,{\"fe",
"e\":10000000,\"price_per_kbyte\":10}],[16,{",
"\"fee\":10000000,\"price_per_kbyte\":10}],[1",
"7,{\"fee\":10000000}],[18,{\"fee\":10000000}",
"],[19,{\"fee\":10000000}],[20,{\"fee\":10000",
"000,\"price_per_kbyte\":10}],[21,{\"fee\":0}",
"],[22,{\"fee\":10000000}],[23,{\"fee\":10000",
"000}],[24,{\"fee\":100000000,\"price_per_kb",
"yte\":10}],[25,{\"fee\":100000000}],[26,{\"f",
"ee\":0}],[27,{\"fee\":0}],[28,{\"fee\":0}],[2",
"9,{\"fee\":0}],[30,{\"fee\":0}],[31,{\"fee\":0",
"}],[32,{\"fee\":0}],[33,{\"fee\":0}],[34,{\"f",
"ee\":0}],[35,{\"fee\":0}],[36,{\"fee\":0}]],\"",
"scale\":10000},\"block_interval\":5,\"mainte",
"nance_interval\":86400,\"maintenance_skip_",
"slots\":3,\"witness_proposal_review_period",
"\":1209600,\"maximum_transaction_size\":204",
"8,\"maximum_block_size\":2048000000,\"maxim",
"um_time_until_expiration\":86400,\"maximum",
"_proposal_lifetime\":2419200,\"maximum_ass",
"et_feed_publishers\":10,\"maximum_witness_",
"count\":1001,\"maximum_authority_membershi",
"p\":10,\"reserve_percent_of_fee\":2000,\"net",
"work_percent_of_fee\":2000,\"lifetime_refe",
"rrer_percent_of_fee\":3000,\"cashback_vest",
"ing_period_seconds\":31536000,\"cashback_v",
"esting_threshold\":\"10000000000\",\"count_n",
"on_member_votes\":true,\"allow_non_member_",
"whitelists\":false,\"max_predicate_opcode\"",
":1,\"fee_liquidation_threshold\":100000000",
",\"accounts_per_fee_scale\":1000,\"account_",
"fee_scale_bitshifts\":4,\"max_authority_de",
"pth\":2,\"extensions\":[]},\"initial_account",
"s\":[{\"name\":\"init0\",\"owner_key\":\"DCT82MT",
"CQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1",
"CpCwKy\",\"active_key\":\"DCT82MTCQVa9TDFmz3",
"ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCwKy\"},{\"",
"name\":\"init1\",\"owner_key\":\"DCT82MTCQVa9T",
"DFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCwKy",
"\",\"active_key\":\"DCT82MTCQVa9TDFmz3ZwaLzs",
"FAmCLoJzrtFugpF72vsbuE1CpCwKy\"},{\"name\":",
"\"init2\",\"owner_key\":\"DCT82MTCQVa9TDFmz3Z",
"waLzsFAmCLoJzrtFugpF72vsbuE1CpCwKy\",\"act",
"ive_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLo",
"JzrtFugpF72vsbuE1CpCwKy\"},{\"name\":\"init3",
"\",\"owner_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsF",
"AmCLoJzrtFugpF72vsbuE1CpCwKy\",\"active_ke",
"y\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFu",
"gpF72vsbuE1CpCwKy\"},{\"name\":\"init4\",\"own",
"er_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJ",
"zrtFugpF72vsbuE1CpCwKy\",\"active_key\":\"DC",
"T82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72v",
"sbuE1CpCwKy\"},{\"name\":\"init5\",\"owner_key",
"\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFug",
"pF72vsbuE1CpCwKy\",\"active_key\":\"DCT82MTC",
"QVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1C",
"pCwKy\"},{\"name\":\"init6\",\"owner_key\":\"DCT",
"82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vs",
"buE1CpCwKy\",\"active_key\":\"DCT82MTCQVa9TD",
"Fmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCwKy\"",
"},{\"name\":\"init7\",\"owner_key\":\"DCT82MTCQ",
"Va9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1Cp",
"CwKy\",\"active_key\":\"DCT82MTCQVa9TDFmz3Zw",
"aLzsFAmCLoJzrtFugpF72vsbuE1CpCwKy\"},{\"na",
"me\":\"init8\",\"owner_key\":\"DCT82MTCQVa9TDF",
"mz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCwKy\",",
"\"active_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFA",
"mCLoJzrtFugpF72vsbuE1CpCwKy\"},{\"name\":\"i",
"nit9\",\"owner_key\":\"DCT82MTCQVa9TDFmz3Zwa",
"LzsFAmCLoJzrtFugpF72vsbuE1CpCwKy\",\"activ",
"e_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJz",
"rtFugpF72vsbuE1CpCwKy\"},{\"name\":\"init10\"",
",\"owner_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFA",
"mCLoJzrtFugpF72vsbuE1CpCwKy\",\"active_key",
"\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFug",
"pF72vsbuE1CpCwKy\"},{\"name\":\"decent\",\"own",
"er_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJ",
"zrtFugpF72vsbuE1CpCwKy\",\"active_key\":\"DC",
"T82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72v",
"sbuE1CpCwKy\"}],\"initial_assets\":[],\"init",
"ial_active_witnesses\":11,\"initial_witnes",
"s_candidates\":[{\"owner_name\":\"init0\",\"bl",
"ock_signing_key\":\"DCT82MTCQVa9TDFmz3ZwaL",
"zsFAmCLoJzrtFugpF72vsbuE1CpCwKy\"},{\"owne",
"r_name\":\"init1\",\"block_signing_key\":\"DCT",
"82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vs",
"buE1CpCwKy\"},{\"owner_name\":\"init2\",\"bloc",
"k_signing_key\":\"DCT82MTCQVa9TDFmz3ZwaLzs",
"FAmCLoJzrtFugpF72vsbuE1CpCwKy\"},{\"owner_",
"name\":\"init3\",\"block_signing_key\":\"DCT82",
"MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbu",
"E1CpCwKy\"},{\"owner_name\":\"init4\",\"block_",
"signing_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFA",
"mCLoJzrtFugpF72vsbuE1CpCwKy\"},{\"owner_na",
"me\":\"init5\",\"block_signing_key\":\"DCT82MT",
"CQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1",
"CpCwKy\"},{\"owner_name\":\"init6\",\"block_si",
"gning_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmC",
"LoJzrtFugpF72vsbuE1CpCwKy\"},{\"owner_name",
"\":\"init7\",\"block_signing_key\":\"DCT82MTCQ",
"Va9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1Cp",
"CwKy\"},{\"owner_name\":\"init8\",\"block_sign",
"ing_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLo",
"JzrtFugpF72vsbuE1CpCwKy\"},{\"owner_name\":",
"\"init9\",\"block_signing_key\":\"DCT82MTCQVa",
"9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCw",
"Ky\"},{\"owner_name\":\"init10\",\"block_signi",
"ng_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJ",
"zrtFugpF72vsbuE1CpCwKy\"}],\"initial_chain",
"_id\":\"9a5e5be357cdfa2c48dbe260f983a0109b",
"52b9afdada705521cddad9243522f7\",\"initial",
"_balances\":[{\"owner\":\"decent\",\"asset_sym",
"bol\":\"DCT\",\"amount\":\"4000000000000000\"}]",
",\"immutable_parameters\":{\"min_witness_co",
"unt\":11,\"num_special_accounts\":0,\"num_sp",
"ecial_assets\":0}}"
};

chain_id_type get_egenesis_chain_id()
{
   return chain_id_type( "6af7b83a55a87b52d038aaf9584402edb4ec7624c1b0ec6c80b008e7987f86f2" );
}

void compute_egenesis_json( std::string& result )
{
   result.reserve( 5257 );
   result.resize(0);
   for( size_t i=0; i<132-1; i++ )
   {
      result.append( genesis_json_array[i], 40 );
   }
   result.append( std::string( genesis_json_array[ 132-1 ] ) );
   return;
}

fc::sha256 get_egenesis_json_hash()
{
   return fc::sha256( "6af7b83a55a87b52d038aaf9584402edb4ec7624c1b0ec6c80b008e7987f86f2" );
}

} }
