//                                   _           _    __ _ _        //
//                                  | |         | |  / _(_) |       //
//    __ _  ___ _ __   ___ _ __ __ _| |_ ___  __| | | |_ _| | ___   //
//   / _` |/ _ \ '_ \ / _ \ '__/ _` | __/ _ \/ _` | |  _| | |/ _ \  //
//  | (_| |  __/ | | |  __/ | | (_| | ||  __/ (_| | | | | | |  __/  //
//   \__, |\___|_| |_|\___|_|  \__,_|\__\___|\__,_| |_| |_|_|\___|  //
//    __/ |                                                         //
//   |___/                                                          //
//                                                                  //
// Generated by:  libraries/chain_id/identify_chain.cpp             //
//                                                                  //
// Warning: This is a generated file, any changes made here will be //
// overwritten by the build process.  If you need to change what    //
// is generated here, you should use the CMake variable             //
// GRAPHENE_EGENESIS_JSON to specify an embedded genesis state.     //
//                                                                  //

/*
 * Copyright (c) 2015, Cryptonomex, Inc.
 * All rights reserved.
 *
 * This source code is provided for evaluation in private test networks only, until September 8, 2015. After this date, this license expires and
 * the code may not be used, modified or distributed for any purpose. Redistribution and use in source and binary forms, with or without modification,
 * are permitted until September 8, 2015, provided that the following conditions are met:
 *
 * 1. The code and/or derivative works are used only for private test networks consisting of no more than 10 P2P nodes.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <graphene/chain/protocol/types.hpp>
#include <graphene/egenesis/egenesis.hpp>

namespace graphene { namespace egenesis {

using namespace graphene::chain;

static const char genesis_json_array[132][40+1] =
{
"{\"initial_timestamp\":\"2017-03-07T09:03:4",
"5\",\"max_core_supply\":\"6000000000000000\",",
"\"initial_parameters\":{\"current_fees\":{\"p",
"arameters\":[[0,{\"fee\":10000000,\"price_pe",
"r_kbyte\":1000000000}],[1,{\"fee\":10000000",
"}],[2,{\"fee\":0}],[3,{}],[4,{\"basic_fee\":",
"500000000,\"premium_fee\":2000000000,\"pric",
"e_per_kbyte\":100000000}],[5,{\"fee\":10000",
"0000,\"price_per_kbyte\":100000000}],[6,{\"",
"fee\":500000000}],[7,{\"symbol3\":\"50000000",
"000\",\"symbol4\":\"20000000000\",\"long_symbo",
"l\":500000000,\"price_per_kbyte\":10}],[8,{",
"\"fee\":200000000,\"price_per_kbyte\":10}],[",
"9,{\"fee\":100000000}],[10,{\"fee\":20000000",
"0,\"price_per_kbyte\":100000000}],[11,{\"fe",
"e\":1}],[12,{\"fee\":\"5000000000\"}],[13,{\"f",
"ee\":200000000}],[14,{\"fee\":10}],[15,{\"fe",
"e\":10000000,\"price_per_kbyte\":10}],[16,{",
"\"fee\":10000000,\"price_per_kbyte\":10}],[1",
"7,{\"fee\":10000000}],[18,{\"fee\":10000000}",
"],[19,{\"fee\":10000000}],[20,{\"fee\":10000",
"000,\"price_per_kbyte\":10}],[21,{\"fee\":0}",
"],[22,{\"fee\":10000000}],[23,{\"fee\":10000",
"000}],[24,{\"fee\":100000000,\"price_per_kb",
"yte\":10}],[25,{\"fee\":100000000}],[26,{\"f",
"ee\":0}],[27,{\"fee\":0}],[28,{\"fee\":0}],[2",
"9,{\"fee\":0}],[30,{\"fee\":0}],[31,{\"fee\":0",
"}],[32,{\"fee\":0}],[33,{\"fee\":0}],[34,{\"f",
"ee\":0}],[35,{\"fee\":0}]],\"scale\":10000},\"",
"block_interval\":5,\"maintenance_interval\"",
":86400,\"maintenance_skip_slots\":3,\"witne",
"ss_proposal_review_period\":1209600,\"maxi",
"mum_transaction_size\":2048,\"maximum_bloc",
"k_size\":2048000000,\"maximum_time_until_e",
"xpiration\":86400,\"maximum_proposal_lifet",
"ime\":2419200,\"maximum_asset_feed_publish",
"ers\":10,\"maximum_witness_count\":1001,\"ma",
"ximum_authority_membership\":10,\"reserve_",
"percent_of_fee\":2000,\"network_percent_of",
"_fee\":2000,\"lifetime_referrer_percent_of",
"_fee\":3000,\"cashback_vesting_period_seco",
"nds\":31536000,\"cashback_vesting_threshol",
"d\":\"10000000000\",\"count_non_member_votes",
"\":true,\"allow_non_member_whitelists\":fal",
"se,\"max_predicate_opcode\":1,\"fee_liquida",
"tion_threshold\":100000000,\"accounts_per_",
"fee_scale\":1000,\"account_fee_scale_bitsh",
"ifts\":4,\"max_authority_depth\":2,\"extensi",
"ons\":[]},\"initial_accounts\":[{\"name\":\"in",
"it0\",\"owner_key\":\"DCT82MTCQVa9TDFmz3ZwaL",
"zsFAmCLoJzrtFugpF72vsbuE1CpCwKy\",\"active",
"_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzr",
"tFugpF72vsbuE1CpCwKy\"},{\"name\":\"init1\",\"",
"owner_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmC",
"LoJzrtFugpF72vsbuE1CpCwKy\",\"active_key\":",
"\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF",
"72vsbuE1CpCwKy\"},{\"name\":\"init2\",\"owner_",
"key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrt",
"FugpF72vsbuE1CpCwKy\",\"active_key\":\"DCT82",
"MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbu",
"E1CpCwKy\"},{\"name\":\"init3\",\"owner_key\":\"",
"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF7",
"2vsbuE1CpCwKy\",\"active_key\":\"DCT82MTCQVa",
"9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCw",
"Ky\"},{\"name\":\"init4\",\"owner_key\":\"DCT82M",
"TCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE",
"1CpCwKy\",\"active_key\":\"DCT82MTCQVa9TDFmz",
"3ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCwKy\"},{",
"\"name\":\"init5\",\"owner_key\":\"DCT82MTCQVa9",
"TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCwK",
"y\",\"active_key\":\"DCT82MTCQVa9TDFmz3ZwaLz",
"sFAmCLoJzrtFugpF72vsbuE1CpCwKy\"},{\"name\"",
":\"init6\",\"owner_key\":\"DCT82MTCQVa9TDFmz3",
"ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCwKy\",\"ac",
"tive_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCL",
"oJzrtFugpF72vsbuE1CpCwKy\"},{\"name\":\"init",
"7\",\"owner_key\":\"DCT82MTCQVa9TDFmz3ZwaLzs",
"FAmCLoJzrtFugpF72vsbuE1CpCwKy\",\"active_k",
"ey\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtF",
"ugpF72vsbuE1CpCwKy\"},{\"name\":\"init8\",\"ow",
"ner_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLo",
"JzrtFugpF72vsbuE1CpCwKy\",\"active_key\":\"D",
"CT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72",
"vsbuE1CpCwKy\"},{\"name\":\"init9\",\"owner_ke",
"y\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFu",
"gpF72vsbuE1CpCwKy\",\"active_key\":\"DCT82MT",
"CQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1",
"CpCwKy\"},{\"name\":\"init10\",\"owner_key\":\"D",
"CT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72",
"vsbuE1CpCwKy\",\"active_key\":\"DCT82MTCQVa9",
"TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCwK",
"y\"},{\"name\":\"decent\",\"owner_key\":\"DCT82M",
"TCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE",
"1CpCwKy\",\"active_key\":\"DCT82MTCQVa9TDFmz",
"3ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCwKy\"}],",
"\"initial_assets\":[],\"initial_active_witn",
"esses\":11,\"initial_witness_candidates\":[",
"{\"owner_name\":\"init0\",\"block_signing_key",
"\":\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFug",
"pF72vsbuE1CpCwKy\"},{\"owner_name\":\"init1\"",
",\"block_signing_key\":\"DCT82MTCQVa9TDFmz3",
"ZwaLzsFAmCLoJzrtFugpF72vsbuE1CpCwKy\"},{\"",
"owner_name\":\"init2\",\"block_signing_key\":",
"\"DCT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF",
"72vsbuE1CpCwKy\"},{\"owner_name\":\"init3\",\"",
"block_signing_key\":\"DCT82MTCQVa9TDFmz3Zw",
"aLzsFAmCLoJzrtFugpF72vsbuE1CpCwKy\"},{\"ow",
"ner_name\":\"init4\",\"block_signing_key\":\"D",
"CT82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72",
"vsbuE1CpCwKy\"},{\"owner_name\":\"init5\",\"bl",
"ock_signing_key\":\"DCT82MTCQVa9TDFmz3ZwaL",
"zsFAmCLoJzrtFugpF72vsbuE1CpCwKy\"},{\"owne",
"r_name\":\"init6\",\"block_signing_key\":\"DCT",
"82MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vs",
"buE1CpCwKy\"},{\"owner_name\":\"init7\",\"bloc",
"k_signing_key\":\"DCT82MTCQVa9TDFmz3ZwaLzs",
"FAmCLoJzrtFugpF72vsbuE1CpCwKy\"},{\"owner_",
"name\":\"init8\",\"block_signing_key\":\"DCT82",
"MTCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbu",
"E1CpCwKy\"},{\"owner_name\":\"init9\",\"block_",
"signing_key\":\"DCT82MTCQVa9TDFmz3ZwaLzsFA",
"mCLoJzrtFugpF72vsbuE1CpCwKy\"},{\"owner_na",
"me\":\"init10\",\"block_signing_key\":\"DCT82M",
"TCQVa9TDFmz3ZwaLzsFAmCLoJzrtFugpF72vsbuE",
"1CpCwKy\"}],\"initial_chain_id\":\"9a5e5be35",
"7cdfa2c48dbe260f983a0109b52b9afdada70552",
"1cddad9243522f7\",\"initial_balances\":[{\"o",
"wner\":\"decent\",\"asset_symbol\":\"DECENT\",\"",
"amount\":\"4000000000000000\"}],\"immutable_",
"parameters\":{\"min_witness_count\":11,\"num",
"_special_accounts\":0,\"num_special_assets",
"\":0}}"
};

chain_id_type get_egenesis_chain_id()
{
   return chain_id_type( "e7632082c36ab13bc16afc5dc3d6fd2e8fde08a7e5489823a4b8f5fc4c5dd5cc" );
}

void compute_egenesis_json( std::string& result )
{
   result.reserve( 5245 );
   result.resize(0);
   for( size_t i=0; i<132-1; i++ )
   {
      result.append( genesis_json_array[i], 40 );
   }
   result.append( std::string( genesis_json_array[ 132-1 ] ) );
   return;
}

fc::sha256 get_egenesis_json_hash()
{
   return fc::sha256( "e7632082c36ab13bc16afc5dc3d6fd2e8fde08a7e5489823a4b8f5fc4c5dd5cc" );
}

} }
