/* (c) 2016, 2017 DECENT Services. For details refers to LICENSE.txt */
/*
 * Copyright (c) 2015 Cryptonomex, Inc., and contributors.
 *
 * The MIT License
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include <graphene/chain/get_config.hpp>
#include <graphene/chain/config.hpp>
#include <graphene/chain/protocol/types.hpp>

namespace graphene { namespace chain {

configuration get_configuration()
{
   return {
      GRAPHENE_SYMBOL,
      GRAPHENE_ADDRESS_PREFIX,
      GRAPHENE_MIN_ACCOUNT_NAME_LENGTH,
      GRAPHENE_MAX_ACCOUNT_NAME_LENGTH,
      GRAPHENE_MIN_ASSET_SYMBOL_LENGTH,
      GRAPHENE_MAX_ASSET_SYMBOL_LENGTH,
      GRAPHENE_MAX_SHARE_SUPPLY,
      GRAPHENE_MAX_PAY_RATE,
      GRAPHENE_MAX_SIG_CHECK_DEPTH,
      GRAPHENE_MIN_TRANSACTION_SIZE_LIMIT,
      GRAPHENE_MIN_BLOCK_INTERVAL,
      GRAPHENE_MAX_BLOCK_INTERVAL,
      GRAPHENE_DEFAULT_BLOCK_INTERVAL,
      GRAPHENE_DEFAULT_MAX_TRANSACTION_SIZE,
      GRAPHENE_DEFAULT_MAX_BLOCK_SIZE,
      GRAPHENE_DEFAULT_MAX_TIME_UNTIL_EXPIRATION,
      GRAPHENE_DEFAULT_MAINTENANCE_INTERVAL,
      GRAPHENE_DEFAULT_MAINTENANCE_SKIP_SLOTS,
      GRAPHENE_MIN_UNDO_HISTORY,
      GRAPHENE_MAX_UNDO_HISTORY,
      GRAPHENE_MIN_BLOCK_SIZE_LIMIT,
      GRAPHENE_MIN_TRANSACTION_EXPIRATION_LIMIT,
      GRAPHENE_BLOCKCHAIN_PRECISION,
      GRAPHENE_BLOCKCHAIN_PRECISION_DIGITS,
      GRAPHENE_DEFAULT_TRANSFER_FEE,
      GRAPHENE_MAX_INSTANCE_ID,
      GRAPHENE_100_PERCENT,
      GRAPHENE_1_PERCENT,
      GRAPHENE_MAX_MARKET_FEE_PERCENT,
      GRAPHENE_DEFAULT_FORCE_SETTLEMENT_DELAY,
      GRAPHENE_DEFAULT_FORCE_SETTLEMENT_OFFSET,
      GRAPHENE_DEFAULT_FORCE_SETTLEMENT_MAX_VOLUME,
      GRAPHENE_DEFAULT_PRICE_FEED_LIFETIME,
      GRAPHENE_MAX_FEED_PRODUCERS,
      GRAPHENE_DEFAULT_MAX_AUTHORITY_MEMBERSHIP,
      GRAPHENE_DEFAULT_MAX_ASSET_WHITELIST_AUTHORITIES,
      GRAPHENE_DEFAULT_MAX_ASSET_FEED_PUBLISHERS,
      GRAPHENE_COLLATERAL_RATIO_DENOM,
      GRAPHENE_MIN_COLLATERAL_RATIO,
      GRAPHENE_MAX_COLLATERAL_RATIO,
      GRAPHENE_DEFAULT_MAINTENANCE_COLLATERAL_RATIO,
      GRAPHENE_DEFAULT_MAX_SHORT_SQUEEZE_RATIO,
      GRAPHENE_DEFAULT_MARGIN_PERIOD_SEC,
      GRAPHENE_DEFAULT_MAX_MINERS,
      GRAPHENE_DEFAULT_MAX_PROPOSAL_LIFETIME_SEC,
      GRAPHENE_DEFAULT_MINER_PROPOSAL_REVIEW_PERIOD_SEC,
      GRAPHENE_DEFAULT_NETWORK_PERCENT_OF_FEE,
      GRAPHENE_DEFAULT_LIFETIME_REFERRER_PERCENT_OF_FEE,
      GRAPHENE_DEFAULT_MAX_BULK_DISCOUNT_PERCENT,
      GRAPHENE_DEFAULT_BULK_DISCOUNT_THRESHOLD_MIN,
      GRAPHENE_DEFAULT_BULK_DISCOUNT_THRESHOLD_MAX,
      GRAPHENE_DEFAULT_CASHBACK_VESTING_PERIOD_SEC,
      GRAPHENE_DEFAULT_CASHBACK_VESTING_THRESHOLD,
      GRAPHENE_DEFAULT_BURN_PERCENT_OF_FEE,
      GRAPHENE_MINER_PAY_PERCENT_PRECISION,
      GRAPHENE_DEFAULT_MAX_ASSERT_OPCODE,
      GRAPHENE_DEFAULT_FEE_LIQUIDATION_THRESHOLD,
      GRAPHENE_DEFAULT_ACCOUNTS_PER_FEE_SCALE,
      GRAPHENE_DEFAULT_ACCOUNT_FEE_SCALE_BITSHIFTS,
      GRAPHENE_MAX_WORKER_NAME_LENGTH,
      GRAPHENE_MAX_URL_LENGTH,
      GRAPHENE_NEAR_SCHEDULE_CTR_IV,
      GRAPHENE_FAR_SCHEDULE_CTR_IV,
      GRAPHENE_CORE_ASSET_CYCLE_RATE,
      GRAPHENE_CORE_ASSET_CYCLE_RATE_BITS,
      GRAPHENE_DEFAULT_MINER_PAY_PER_BLOCK,
      GRAPHENE_DEFAULT_MINER_PAY_VESTING_SECONDS,
      GRAPHENE_MAX_INTEREST_APR,
      GRAPHENE_MINER_ACCOUNT,
      GRAPHENE_NULL_ACCOUNT,
      GRAPHENE_TEMP_ACCOUNT
   };
}

} } // graphene::chain
